#-------------------------------
# General Site Settings
title: Cesar Valades
logo: logo.svg # You can add own logo.
description: Personal Website of Cesar Valades.


#-------------------------------
# Author Settings
author:
  name: Cesar Augusto Valades-Cruz
  image: 01.jpg
  say-hello: Hello, I’m <strong>Cesar Valades</strong>
  bio: Postdoctoral Researcher and Bioimage Analyst at <strong><a style="color:red" href="https://team.inria.fr/serpico/team-members/">Serpico/STED Team</a></strong> of <strong><a  style="color:black" href="https://science.institut-curie.org/"> Curie Institute</a></strong> and <strong><a  style="color:black" href="https://www.inria.fr/en">Inria Rennes - Bretagne Atlantique</a></strong>. <strong><a style="color:red">Loves</a></strong> microscopy, image analysis, basketball & dancing.


#-------------------------------
# Contact links
twitter: https://twitter.com/CessVala # Add your Twitter handle
github: https://github.com/CessVala/ 
linkedin: https://www.linkedin.com/in/cesarvalades/
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
#instagram: https://instagram.com/ # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle

#-------------------------------
# Google Analytics
google-analytics: UA-218917873-1  # Add your identifier. For example UA-99631805-1.
